### ISSUE TITLE
Developer workflow checklist [WIP]

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/docker-compose-wordpress#36]
Some challenges developers face:

- [ ] Moving things between local machine and remote server
- [ ] Efficient mysql export (mysqldump) and import
- [ ] Copying large `wp-content/uploads` folder (nginx proxy hack)
- [ ] Keeping track of HTTP password (hint: nginx + Google auth for org domain would help)

**Comment by PatelUtkarsh** [comment]
If we can use `wp-cli` command with file input and output that would be great.

**Comment by mbtamuli** [comment]
https://github.com/clems4ever/authelia We should try this once.

**Comment by rahul286** [comment]
I would prefer Google Apps login e.g. https://github.com/bitly/oauth2_proxy

**Comment by PatelUtkarsh** [comment]
>Moving things between local machine and remote server

Check https://github.com/10up/wpsnapshots.

**Comment by rahul286** [comment]
@PatelUtkarsh It forces S3 usage. We need more options and freedom!  :) 

I think we should have created separate issues here!
