### ISSUE TITLE
Running WordPress Multisite using docker (compose)

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/docker-compose-wordpress#4]
**Tasks**

- [x] Test WordPress Multisite in subdir mode
- [x] Test WordPress Multisite in subdomain mode
- [x] Test WordPress Multisite with domain mapping

**Tests**

The test must have:

- [x] theme/plugin/core add/remove/update test 
- [x] wp-content/uploads persistence
- [x] database persistence test.

**Comment by mbtamuli** [comment]
Issue to be closed after testing.

[WordPress Multisite](https://github.com/EasyEngine/docker-compose-wordpress/tree/master/wp-multisite) is ready for testing. The test cases are in the description. After testing comment on this issue.

**Comment by mbtamuli** [comment]
Outdated version of ee4
